### ISSUE TITLE
Extension does not model value[x]

### ISSUE THREAD

**Issue by iamtheschmitzer** [samply/golang-fhir-models#12]
In the docs for [Extensibility](https://www.hl7.org/fhir/extensibility.html) it reads 

> The value[x] element has an actual name of "value" and then the TitleCased name of one of these defined types, and its contents are those as defined for that type:
valueBase64Binary: [base64Binary](https://www.hl7.org/fhir/datatypes.html#base64Binary)
valueBoolean: [boolean](https://www.hl7.org/fhir/datatypes.html#boolean)
valueCanonical: [canonical](https://www.hl7.org/fhir/datatypes.html#canonical)
...

The Extension type does not provide for the values, which is the useful part of the extension

**Comment by ivan-navi-studios** [comment]
+1 just experienced this on the questionnaire resource when defining the items. Ended up rebuilding the struct and providing custom struct where required.

**Comment by PontusNyberg** [comment]
Had the same issue on QuestionnaireResponse, Had to made my own custom QuestionnaireResponse structs.
I solved it with adding a "QuestionnaireResponseItemAnswerValue" that takes a value and type. Currently the value is an interface but could easily be replaced with a generic. 
I'll make a PR later.

**Comment by benbpyle** [comment]
I find myself in the same position.  I'm looking at Race and Ethnicity and that is solved by a ValueCoding (https://hl7.org/fhir/R4B/extensibility.html).   Any suggestions or ideas beyond modeling my own struct?

**Comment by alexanderkiel** [comment]
Closed by: 7e79427962ec150495b2a11a4d1a181ba3ab59bb
