### ISSUE TITLE
MarshalJSON escapes HTML characters

### ISSUE THREAD

**Issue by michaelsauter** [samply/golang-fhir-models#13]
https://github.com/samply/golang-fhir-models/blob/master/fhir-models-gen/cmd/valueSet.go#L60 and https://github.com/samply/golang-fhir-models/blob/master/fhir-models-gen/cmd/genResources.go#L277 encode HTML characters deemed problematic (`&`, `<`, and `>`), because that is the default behaviour of `json.Marshal`. This behaviour can be turned off by using a custom encoder, see https://pkg.go.dev/encoding/json#Encoder.SetEscapeHTML.

There are certain fields in the FHIR models which contain those "problematic" characters, but they must not be escaped. For example, http://hl7.org/fhir/R4B/valueset-quantity-comparator.html and the `div` field of http://hl7.org/fhir/R4B/narrative.html.

I have a fix for this at https://github.com/michaelsauter/golang-fhir-models/commit/b45358a.

So far I've been working based on https://github.com/lifebox-healthcare/golang-fhir-models, as it contains PR #7, which I need for my work as well. @alexanderkiel I am wondering if the `samply` repo is still maintained? If not, can we somehow designate what the "main" fork is going forward so that all changes go in there? I detected a bunch of other issues and have fixes for them locally as well (wrong `value` decimal type, spelling of ID fields, gen script issues and FHIR v4.3.0 compatibility).

FYI @frankoid https://github.com/lifebox-healthcare/golang-fhir-models does not have issues enabled, otherwise I could open issues there as well (if the `samply` repo is not maintained). If your fork isn't maintained either, I'm going to open a new fork, enable issues there and push my fixes.

**Comment by frankoid** [comment]
Hi @michaelsauter, I'm not working for LifeBox Healthcare any more so I'm not personally maintaining it, however I'll mention @brentmurphy @nickbrockett and @davemackintosh in case they are interested.

**Comment by michaelsauter** [comment]
Since there hasn't been any update, I forked to https://github.com/BIX-Digital/golang-fhir-models and applied the following main changes:

* [Use ID, not Id](https://github.com/BIX-Digital/golang-fhir-models/commit/1a83f09517f34739b88f8db968f8f325caf754d9)
* [Use float64 for decimal type](https://github.com/BIX-Digital/golang-fhir-models/commit/966d61fcafaf163a2762d554dc7b35767d7ea1ab)
* [Fix gen-resources.sh scripts](https://github.com/BIX-Digital/golang-fhir-models/commit/a6cf5b274f8c44e6fd5fbeef498151a06276273d)
* [Do not escape HTML characters inside JSON quoted strings](https://github.com/BIX-Digital/golang-fhir-models/commit/b45358abed2610c26cd089e3bde98c8dd5d96b81)
