### ISSUE TITLE
Missing "event Coding" in messageheader

### ISSUE THREAD

**Issue by vamsik27** [samply/golang-fhir-models#6]
Thanks for the code 

While using this library found that it is missing eventCoding in the message Header as per the standards in the hl7 URL. Felt like it would be nice to address and once it is updated it will be useful for parsing out that information in my code as well.

http://hl7.org/fhir/R4/messageheader.html.
{
  "resourceType" : "MessageHeader",
  // from Resource: id, meta, implicitRules, and language
  // from DomainResource: text, contained, extension, and modifierExtension
  // event[x]: Code for the event this message represents or link to event definition. One of these 2:
  "eventCoding" : { Coding },
..................
//ignoring remaining fields
}
Any suggestions will be helpful

**Comment by alexanderkiel** [comment]
Closed by: 7e79427962ec150495b2a11a4d1a181ba3ab59bb
